// Code generated by entc, DO NOT EDIT.

package fieldtest

const (
	// Label holds the string label denoting the fieldtest type in the database.
	Label = "field_test"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDateD holds the string denoting the date_d field in the database.
	FieldDateD = "date_d"
	// FieldDate holds the string denoting the date field in the database.
	FieldDate = "date"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldJF holds the string denoting the j_f field in the database.
	FieldJF = "j_f"
	// FieldJSF holds the string denoting the j_s_f field in the database.
	FieldJSF = "j_s_f"
	// FieldAppID holds the string denoting the app_id field in the database.
	FieldAppID = "app_id"
	// Table holds the table name of the fieldtest in the database.
	Table = "field_tests"
)

// Columns holds all SQL columns for fieldtest fields.
var Columns = []string{
	FieldID,
	FieldDateD,
	FieldDate,
	FieldTitle,
	FieldJF,
	FieldJSF,
	FieldAppID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
