// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Admin is the predicate function for admin builders.
type Admin func(*sql.Selector)

// Bee is the predicate function for bee builders.
type Bee func(*sql.Selector)

// Car is the predicate function for car builders.
type Car func(*sql.Selector)

// Cat is the predicate function for cat builders.
type Cat func(*sql.Selector)

// FieldTest is the predicate function for fieldtest builders.
type FieldTest func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
