// Code generated by "stringer -type Status,Color"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Offline-0]
	_ = x[Online-1]
	_ = x[Disable-2]
	_ = x[Deleted-3]
}

const _Status_name = "OfflineOnlineDisableDeleted"

var _Status_index = [...]uint8{0, 7, 13, 20, 27}

func (i Status) String() string {
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Write-0]
	_ = x[Red-1]
	_ = x[Blue-2]
}

const _Color_name = "WriteRedBlue"

var _Color_index = [...]uint8{0, 5, 8, 12}

func (i Color) String() string {
	if i < 0 || i >= Color(len(_Color_index)-1) {
		return "Color(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Color_name[_Color_index[i]:_Color_index[i+1]]
}
