// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"pocket_lab/ent/ent/admin"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// Admin is the model entity for the Admin schema.
type Admin struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Age holds the value of the "age" field.
	Age int `json:"age,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AdminQuery when eager-loading is set.
	Edges     AdminEdges `json:"edges"`
	admin_son *int
}

// AdminEdges holds the relations/edges for other nodes in the graph.
type AdminEdges struct {
	// Cats holds the value of the cats edge.
	Cats []*Cat `json:"cats,omitempty"`
	// Bees holds the value of the bees edge.
	Bees []*Bee `json:"bees,omitempty"`
	// Parent holds the value of the parent edge.
	Parent *Admin `json:"parent,omitempty"`
	// Son holds the value of the son edge.
	Son *Admin `json:"son,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// CatsOrErr returns the Cats value or an error if the edge
// was not loaded in eager-loading.
func (e AdminEdges) CatsOrErr() ([]*Cat, error) {
	if e.loadedTypes[0] {
		return e.Cats, nil
	}
	return nil, &NotLoadedError{edge: "cats"}
}

// BeesOrErr returns the Bees value or an error if the edge
// was not loaded in eager-loading.
func (e AdminEdges) BeesOrErr() ([]*Bee, error) {
	if e.loadedTypes[1] {
		return e.Bees, nil
	}
	return nil, &NotLoadedError{edge: "bees"}
}

// ParentOrErr returns the Parent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AdminEdges) ParentOrErr() (*Admin, error) {
	if e.loadedTypes[2] {
		if e.Parent == nil {
			// The edge parent was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: admin.Label}
		}
		return e.Parent, nil
	}
	return nil, &NotLoadedError{edge: "parent"}
}

// SonOrErr returns the Son value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AdminEdges) SonOrErr() (*Admin, error) {
	if e.loadedTypes[3] {
		if e.Son == nil {
			// The edge son was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: admin.Label}
		}
		return e.Son, nil
	}
	return nil, &NotLoadedError{edge: "son"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Admin) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case admin.FieldID, admin.FieldAge:
			values[i] = new(sql.NullInt64)
		case admin.FieldName:
			values[i] = new(sql.NullString)
		case admin.ForeignKeys[0]: // admin_son
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Admin", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Admin fields.
func (a *Admin) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case admin.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			a.ID = int(value.Int64)
		case admin.FieldAge:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field age", values[i])
			} else if value.Valid {
				a.Age = int(value.Int64)
			}
		case admin.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				a.Name = value.String
			}
		case admin.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field admin_son", value)
			} else if value.Valid {
				a.admin_son = new(int)
				*a.admin_son = int(value.Int64)
			}
		}
	}
	return nil
}

// QueryCats queries the "cats" edge of the Admin entity.
func (a *Admin) QueryCats() *CatQuery {
	return (&AdminClient{config: a.config}).QueryCats(a)
}

// QueryBees queries the "bees" edge of the Admin entity.
func (a *Admin) QueryBees() *BeeQuery {
	return (&AdminClient{config: a.config}).QueryBees(a)
}

// QueryParent queries the "parent" edge of the Admin entity.
func (a *Admin) QueryParent() *AdminQuery {
	return (&AdminClient{config: a.config}).QueryParent(a)
}

// QuerySon queries the "son" edge of the Admin entity.
func (a *Admin) QuerySon() *AdminQuery {
	return (&AdminClient{config: a.config}).QuerySon(a)
}

// Update returns a builder for updating this Admin.
// Note that you need to call Admin.Unwrap() before calling this method if this Admin
// was returned from a transaction, and the transaction was committed or rolled back.
func (a *Admin) Update() *AdminUpdateOne {
	return (&AdminClient{config: a.config}).UpdateOne(a)
}

// Unwrap unwraps the Admin entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (a *Admin) Unwrap() *Admin {
	tx, ok := a.config.driver.(*txDriver)
	if !ok {
		panic("ent: Admin is not a transactional entity")
	}
	a.config.driver = tx.drv
	return a
}

// String implements the fmt.Stringer.
func (a *Admin) String() string {
	var builder strings.Builder
	builder.WriteString("Admin(")
	builder.WriteString(fmt.Sprintf("id=%v", a.ID))
	builder.WriteString(", age=")
	builder.WriteString(fmt.Sprintf("%v", a.Age))
	builder.WriteString(", name=")
	builder.WriteString(a.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Admins is a parsable slice of Admin.
type Admins []*Admin

func (a Admins) config(cfg config) {
	for _i := range a {
		a[_i].config = cfg
	}
}
