// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"pocket_lab/ent/ent/admin"
	"pocket_lab/ent/ent/cat"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// Cat is the model entity for the Cat schema.
type Cat struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Age holds the value of the "age" field.
	Age int `json:"age,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CatQuery when eager-loading is set.
	Edges      CatEdges `json:"edges"`
	admin_cats *int
}

// CatEdges holds the relations/edges for other nodes in the graph.
type CatEdges struct {
	// Owner holds the value of the owner edge.
	Owner *Admin `json:"owner,omitempty"`
	// Cb holds the value of the cb edge.
	Cb []*Bee `json:"cb,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CatEdges) OwnerOrErr() (*Admin, error) {
	if e.loadedTypes[0] {
		if e.Owner == nil {
			// The edge owner was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: admin.Label}
		}
		return e.Owner, nil
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// CbOrErr returns the Cb value or an error if the edge
// was not loaded in eager-loading.
func (e CatEdges) CbOrErr() ([]*Bee, error) {
	if e.loadedTypes[1] {
		return e.Cb, nil
	}
	return nil, &NotLoadedError{edge: "cb"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Cat) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case cat.FieldID, cat.FieldAge:
			values[i] = new(sql.NullInt64)
		case cat.FieldName:
			values[i] = new(sql.NullString)
		case cat.ForeignKeys[0]: // admin_cats
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Cat", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Cat fields.
func (c *Cat) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case cat.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			c.ID = int(value.Int64)
		case cat.FieldAge:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field age", values[i])
			} else if value.Valid {
				c.Age = int(value.Int64)
			}
		case cat.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				c.Name = value.String
			}
		case cat.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field admin_cats", value)
			} else if value.Valid {
				c.admin_cats = new(int)
				*c.admin_cats = int(value.Int64)
			}
		}
	}
	return nil
}

// QueryOwner queries the "owner" edge of the Cat entity.
func (c *Cat) QueryOwner() *AdminQuery {
	return (&CatClient{config: c.config}).QueryOwner(c)
}

// QueryCb queries the "cb" edge of the Cat entity.
func (c *Cat) QueryCb() *BeeQuery {
	return (&CatClient{config: c.config}).QueryCb(c)
}

// Update returns a builder for updating this Cat.
// Note that you need to call Cat.Unwrap() before calling this method if this Cat
// was returned from a transaction, and the transaction was committed or rolled back.
func (c *Cat) Update() *CatUpdateOne {
	return (&CatClient{config: c.config}).UpdateOne(c)
}

// Unwrap unwraps the Cat entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (c *Cat) Unwrap() *Cat {
	tx, ok := c.config.driver.(*txDriver)
	if !ok {
		panic("ent: Cat is not a transactional entity")
	}
	c.config.driver = tx.drv
	return c
}

// String implements the fmt.Stringer.
func (c *Cat) String() string {
	var builder strings.Builder
	builder.WriteString("Cat(")
	builder.WriteString(fmt.Sprintf("id=%v", c.ID))
	builder.WriteString(", age=")
	builder.WriteString(fmt.Sprintf("%v", c.Age))
	builder.WriteString(", name=")
	builder.WriteString(c.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Cats is a parsable slice of Cat.
type Cats []*Cat

func (c Cats) config(cfg config) {
	for _i := range c {
		c[_i].config = cfg
	}
}
